# .github/workflows/notify.yml
name: Notificación nocturna

on:
  schedule:
    - cron: '*/5 * * * *'  # 5am UTC = 2am Argentina (ART = UTC-3)
  workflow_dispatch:      # permite ejecutarlo manualmente también

jobs:
  send-notification:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Instalar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar dependencias
        run: pip install requests

      - name: Ejecutar script
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python notify.py